### ISSUE TITLE
I cannot submit my first exercise

### ISSUE THREAD

**Issue by maefju** [exercism/cli#119]
Hi,

i tried to submit my first c# exercise today, but when i type "exercism submit year.cs" in my cmd window it displays following error:

goroutine 16 [running]:
runtime.panic(0x724700, 0x931c6f)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0x11f
github.com/exercism/cli/handlers.Submit(0xc08203e210)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/handlers/submit.go:5
9 +0xc3e
github.com/codegangsta/cli.Command.Run(0x770f30, 0x6, 0x770610, 0x1, 0x7d3e70, 0
x34, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/kytrinyx/code/go/src/github.com/codegangsta/cli/command.go:101 +0
xc76
github.com/codegangsta/cli.(*App).Run(0xc0820580c0, 0xc082007bf0, 0x3, 0x3, 0x0,
 0x0)
        /Users/kytrinyx/code/go/src/github.com/codegangsta/cli/app.go:125 +0x948

main.main()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/main.go:116 +0x607

goroutine 19 [finalizer wait]:
runtime.park(0x415900, 0x935638, 0x9337a9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0x935638, 0x9337a9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

I have no idea how to fix this error,

regards maefju

**Comment by kytrinyx** [comment]
Closing for inactivity. Please reopen the issue if you're still having problems.
