### ISSUE TITLE
Issue with running gradle test when using java 11

### ISSUE THREAD

**Issue by jdsingh122918** [exercism/cli#840]
On running gradle test on my linux vm, I am getting the following error:

"FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Exception is:
`java.lang.IllegalArgumentException: Could not determine java version from '11.0.2'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)`

**Comment by jdsingh122918** [comment]
I resolved the issue by reverting to java 8. But I think the cli is still broken with java 11. I am using the OpenJDK version.

**Comment by NobbZ** [comment]
This is not related to the exercism CLI but to gradle and the java track.

/cc @exercism/java

**Comment by Smarticles101** [comment]
Correct, this is an error related to your version of gradle. Try making sure you're using the latest version.

**Comment by kytrinyx** [comment]
I'm going to assume this one is sorted out. @jdsingh122918 if you're still having trouble, please open an issue in http://github.com/exercism/exercism/issues
