### ISSUE TITLE
npm Test Not Working

### ISSUE THREAD

**Issue by LREGS** [exercism/cli#938]
When I run npm test the following occurs:

william@Williams-MacBook-Pro two-fer % npm test

> exercism-javascript@1.2.0 test /Users/william/Exercism/javascript/two-fer
> jest --no-cache ./*

sh: jest: command not found
npm ERR! Test failed.  See above for more details.

Very fresh with this and unsure if my process is even correct. I have followed all the installation guides to the best of my ability. 

I am then downloading and opening the tasks in Atom. I am the completing the tasks in the skeleton file and then running npm test in the terminal once in the correct directory.

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:      /Users/william
Workspace: /Users/william/Exercism
Config:    /Users/william/.config/exercism
API key:   da93*****************************36c

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 45.573214ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 206.019259ms

**Comment by tejasbubane** [comment]
@LREGS Did you run `npm install` inside the `two-fer` directory. Since node modules are installed locally, this has to be done for each exercise. If you are still facing the issue, please open an issue at https://github.com/exercism/javascript/. More people will be able to help you there.

This repo is for the `exercism` command line utility itself.

**Comment by narissa-hajratalli** [comment]
Did anyone figure this out? I am having the same issue. 
`$ npm test

> exercism-javascript@1.1.0 test /Users/narissa.k.hajratalli/Exercism/javascript/hello-world
> jest --no-cache ./*

 FAIL  ./hello-world.spec.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:173:18)

  console.log
    Hello World

      at Object.<anonymous> (hello-world.js:10:9)

  console.log
    Hello

      at Object.<anonymous> (hello-world.spec.js:9:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.979s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/hello-world.js|.\/hello-world.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json/i.
npm ERR! Test failed.  See above for more details.`

I'm also pretty new with this. I'm just trying to set up with the hello world exercise.

**Comment by mohamedmehdigara** [comment]
@tejasbubane I have the same problem with npm. jest command not find. There is no _two-fer_ directory or I can't find it.

**Comment by NobbZ** [comment]
@mohamedmehdigara the `two-fer` folder will be within your `$(exercism workspace)/javascript` folder, if you already downloaded the `two-fer` exercise.

You might have the error on another exercise though, still the summary will remain roughly the same, you need to run `npm install` for each and every exercise you download from within the exercises directory.

**Comment by mohamedmehdigara** [comment]
@NobbZ I understand what you mean. **two-fer** is another exercise. I am stuck in the **hello world** exercise.
![Capture](https://user-images.githubusercontent.com/47916299/101618458-4a947e00-3a12-11eb-875a-9fca1f254c3f.PNG)

**Comment by NobbZ** [comment]
Seems as if there is dependency that hasn't been downloaded properly. Deleting the `node_modules` folder and then running `npm install` again might fix it.

\cc @exercism/javascript perhaps you are a better fit for helping out from now?

**Comment by mohamedmehdigara** [comment]
@NobbZ Where is the node_modules folder?
![Capture2](https://user-images.githubusercontent.com/47916299/101648516-2f3d6900-3a3a-11eb-803c-cf71cdc4cb64.PNG)

**Comment by SleeplessByte** [comment]
@mohamedmehdigara salut 👋🏽 

Did you run `npm install` inside the `hello-world` folder? This must be done from a terminal, such as integrated with vs code, or `cmd.exe`. **Let us know** if "terminal" is unclear, and we can give you a step-by-step guide. It would look something like this:

```shellscript
cd C:\Users\Admin\Exercism\javascript\hello-world
npm install
```

If you run `npm install`, `node_modules` will be added to that directory.

For `two-fer`, it's the same steps. You would go into the folder using your terminal, and then run `npm install`, for example:

```shellscript
cd C:\Users\Admin\Exercism\javascript\two-fer
npm install
```

**Comment by mohamedmehdigara** [comment]
@SleeplessByte  I did
 **cd C:\Users\Admin\Exercism\javascript\hello-world
npm install**
But still there is no npm modules folder and nothing is added. Same as in the screenshot.

**Comment by SleeplessByte** [comment]
> But still there is no npm modules folder and nothing is added. Same as in the screenshot.

Can you give us the _output_ (screenshot is fine) after you do 

```shellscript
cd C:\Users\Admin\Exercism\javascript\hello-world
npm install
```

**Comment by wonka64** [comment]
I get:
$ ls -aFC
./  ../  babel.config.js  .eslintrc  .exercism/  hello-world.js  hello-world.spec.js  .npmrc  package.json  README.md
~/exercism/javascript/hello-world$ npm install
[..................] / idealTree:hello-world: sill idealTree buildDeps

Its stuck there.

I'm on node v15.10.0

**Comment by SleeplessByte** [comment]
@wonka64 that step can take a few minutes, but it could be that something like a virus scanner is interfering with is. Regardless, I do recommend you try again on node 14. (See https://nodejs.org/en/). Uneven node numbers are _never_ stable.

**Comment by tejasbubane** [comment]
@wonka64 Try running `npm install --verbose` and see if you find any errors or check where exactly it gets stuck. Does https://registry.npmjs.org/ work for you in the browser?

**Comment by wonka64** [comment]
Confirmed working on node v15.10.0 in a Linux image on a Chromebook - root cause was a networking issue caused by an Android app.
Thank you @SleeplessByte & @tejasbubane
